spring.kafka:
  bootstrap-servers: localhost:29092
  properties:
    schema.registry.url: http://localhost:28085
  # producer
  producer:
    key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
    value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  # consumer
  consumer:
    group-id: reactivekafkaconsumerandproducer
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
    value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    schema.registry.url: localhost:28085
    # json deserializer config

notification.topic: notification
